name: ejdb2_dart
description: Embeddable JSON Database engine EJDB http://ejdb.org Dart binding
version: 1.0.49
homepage: https://github.com/Softmotions/ejdb
issue_tracker: https://github.com/Softmotions/ejdb/issues?q=is%3Aissue+label%3ADart+
author: Adamansky Anton <adamansky@softmotions.com>
license: MIT

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.6.2
  quiver: ^2.0.3
  json_at: ^1.0.2
